# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KSl223NxhiQ5so78VzMJ_nDRd33NbHYo
"""

frutas = {'uva','maça','banana','pera','uva'}
frutas.remove('maça')
print(frutas)

web = {'htm1','javascript','python','css'}
mobile = {'fluter','python','kotlin','javascript'}
diferenca = web.difference(mobile)
print(diferenca)

a = {1,2,3,4}
 b = {1,4,5,6}
 c = a.union(b)
 c

print(a.intersection(b))

type(a)

carros = {'bmw','amaroque','celta'}
print(f'aqui carros estao em uma lista: {carros}')
carros = set(carros)
print(f'agora carros estao em uma lista: {carros}')
carros = {'bmw','amaroque','celta'}
carros.remove('amaroque')
print(carros)

jogos = {'domino','dama','futebol'}
print(f'aqui jogos estao em uma lista: {jogos}')
jogos = set(jogos)
print(f'agora jogos estao em uma lista: {jogos}')
carros = {'domino','dama','futebol'}
carros.remove('futebol')
print(carros)

jogos = {'domino','dama','futebol'}
print(f'aqui jogos estao em uma lista: {jogos}')
jogos = set(jogos)
print(f'agora jogos estao em uma lista: {jogos}')
a = {'domino','dama','futebol'}
b = {'futsal','baralho','free fire'}
c = a.union(b)
c